services:
  redis:
    container_name: shortest_redis
    hostname: localhost
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - default
    volumes:
      - "./data:/app/data"

  api:
    container_name: shortest_api
    build:
      context: .
      dockerfile: Dockerfile
    image: shortest
    ports:
      - "8000:8000"
    environment:
      - "ENV_FILE=${ENV_FILE}"
    env_file:
      - .env.prod
    depends_on:
      - redis
    networks:
      - default
    volumes:
      - "./data:/app/data"
      - ./:/app
